### PR TITLE
Minigame

### LINKED ISSUE #9: Camera Entity as an Anchor for other entities.
I can't seem to get the player entity (an Anchor w/ .camera as its anchoring) to accept (and display) any child entities.

Notably in the laser branch. Within ViewController.swift, I try to set the TraceTarget as a child of cameraEntity unsuccessfully. I know the code in TraceTarget somewhat works (can display points at least) because it works when I attach it to the groundAncEntity.

### PR DESCRIPTION
**Pull request by erwang01**

### CODE REVIEW

**Review by sanathsengupta — COMMENTED** [review]
The overall code structure looks good, lends itself relatively easily to expanding on the Minigame concept. One thing I think is a bit strange is that everything we are working with is entities -- perhaps we could look into separating the "game logic" from the minigame's physical representation. In this case the game logic isn't too complex -- adding points based on whether or not a collision has occured. But for more complex games, this separation could be important, in which case we may want to establish the precedent now.

**Comment by erwang01** [comment]
How do you suggest we separate the game logic from the physical representation? In particular, what kind of scaffolding does the game logic need?

**Comment by sanathsengupta** [comment]
Perhaps we could implement a MVC type layout. The view and model are already pretty well separated, as is the benefit of Apple’s ViewController framework (we could more explicitly design a “display” and “run” function for each mini game to further emphasize this separation, so that we are not directly interacting with the entity in the View Controller). In terms of the game logic, we could have a separate controller object that contains a state (active/inactive, played/not played) as well as methods that are called on collision (to update score/perform any further action). Also note: this is just me spitballing ideas, not necessarily saying this is the way we should/need to go.

**Comment by erwang01** [comment]
Is this something more like what you are looking for?

**Review by sanathsengupta — COMMENTED** [review]
Yah, this looks good. One question I have is why the Minigame protocol extends Entity, and implementations of the Minigame protocol also separately extend Entity. Is that just a peculiarity with how protocols are defined?

Also, would you mind explaining to me what all the matrix transformations you wrote to get the points placed correctly do? I'm having some trouble understanding exactly what transform to use for board generation .

**Comment by erwang01** [comment]
Yeah that just specifies that the Minigame protocol must be applied on an Entity, however protocols themselves are not allowed to extend classes.

Also there was some issue with making Minigame extend Publisher so I couldn't get it to publish scores. Currently the ViewController still must poll the Minigame Controller which then polls the currentMinigame.

Matrix transformations will be explained in the next commit.

**Pull request merged**
